---
- name: prepare known_hosts entries for all host
  shell: "ssh-keyscan -t rsa {{ hostvars[item].ansible_fqdn }}"
  with_items: "{{ groups['hadoop_cluster'] }}"
  register: keyscans


- debug: msg={{ keyscans.results }}

- debug: msg={{item}}
  with_items: "{{ keyscans.results }}"

- name: prepare known_hosts
  lineinfile: 
    dest=/home/{{ hadoop_user }}/.ssh/known_hosts
    create=yes
    state=present
    line="{{ item.stdout }}"
    regexp="^{{ item[item] }}"
    owner={{ hadoop_user }}
    group={{ hadoop_user }}
  with_items: "{{ keyscans.results }}"

- name: prepare known_hosts entries
  shell: ssh-keyscan -t rsa 0.0.0.0
  register: keyscan_0_0_0_0

- name: add 0.0.0.0 to known_hosts for secondary namenode
  lineinfile: 
    dest=/home/{{ hadoop_user }}/.ssh/known_hosts
    create=yes
    state=present
    line="{{ keyscan_0_0_0_0.stdout }}"
    regexp="^0.0.0.0"
    owner={{ hadoop_user }}
    group={{ hadoop_group }}
