---
postgresql_config_path: "/etc/postgresql/{{ postgresql_version }}/main"
ph_hba_conf: "{{ postgresql_config_path }}/pg_hba.conf"
postgresql_conf: "{{ postgresql_config_path }}/postgresql.conf"
pid_postgresql_path: /var/run/postgresql/9.3-main.pid
postgresql_packages:
  - python-psycopg2
  - "postgresql-{{ postgresql_version }}"
  - "postgresql-contrib-{{ postgresql_version }}"

postgresql_daemon: postgresql
