---
- name: Start namenode service
  shell: "{{ hadoop_services_dir }}/service-namenode.sh"
  args:
    executable: /bin/bash


- name: Start secondary namenode service
  shell: "{{ hadoop_services_dir }}/service-secondary-namenode.sh"
  args:
    executable: /bin/bash
  delegate_to: "{{ item }}"
  with_items: "{{ groups['hadoop_seconday_namenode'] }}"


- name: Start resource manager service
  shell: "{{ hadoop_services_dir }}/service-resource-manager.sh"
  args:
    executable: /bin/bash


- name: Start datanode service
  shell: "{{ hadoop_services_dir }}/service-datanode.sh"
  args:
    executable: /bin/bash
  delegate_to: "{{ item }}"
  with_items: "{{ groups['hadoop_datanodes'] }}"


- name: Start node manager service
  shell: "{{ hadoop_services_dir }}/service-nodemanager.sh"
  args:
    executable: /bin/bash
  delegate_to: "{{ item }}"
  with_items: "{{ groups['hadoop_datanodes'] }}"
