---
- debug: msg={{ webserver_user }}
- name: Create webserver HDFS user directory
  shell: "source /etc/profile && hadoop fs -mkdir -p /usr/{{ webserver_user }}"
  args:
     executable: /bin/bash

- name: Changing permission of webserver HDFS user directory
  shell: "source /etc/profile && hadoop fs -chmod 0755 /usr/{{ webserver_user }}"
  args:
     executable: /bin/bash

- name: Changing ownership of webserver HDFS user directory
  shell: "source /etc/profile && hadoop fs -chown {{ webserver_user }}:{{ webserver_user }} /usr/{{ webserver_user }}"
  args:
     executable: /bin/bash

- name: Create webserver HDFS work directory
  shell: "source /etc/profile && hadoop fs -mkdir -p {{ webserver_hdfs_path }}"
  args:
     executable: /bin/bash

- name: Changing permission of webserver HDFS work directory
  shell: "source /etc/profile && hadoop fs -chmod 0755 {{ webserver_hdfs_path }}"
  args:
     executable: /bin/bash

- name: Changing ownership of webserver HDFS work directory
  shell: "source /etc/profile && hadoop fs -chown {{ webserver_user }}:{{ webserver_user }} {{ webserver_hdfs_path }}"
  args:
     executable: /bin/bash

