---
- include_vars: debian.yml
  when: ansible_os_family == 'Debian'

- include_vars: redhat.yml
  when: ansible_os_family == 'RedHat'

- include: install.yml
- include: configure.yml
- include: service.yml
