---
- name: Gathering Facts
  hosts: all
  gather_facts: False
  become: yes
  become_method: sudo

  tasks:
  - name: Install python 2
    raw: test -e /usr/bin/python || (apt -qqy update && apt install -qqy python-minimal)
