---

- name: Install Postgresql
  package: name={{ item }} state=latest
  with_items: "{{ postgresql_packages }}"


- name: Postgresql initdb (CentOS 6)
  shell: service postgresql initdb
  args:
    creates: "{{ ph_hba_conf }}"
  when: "ansible_os_family == 'RedHat' and ansible_distribution_major_version == '6'"

- name: Postgresql initdb (CentOS 7)
  shell: postgresql-setup initdb
  args:
    creates: "{{ ph_hba_conf }}"
  when: "ansible_os_family == 'RedHat' and ansible_distribution_major_version == '7'"
